[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "treelimb"
version = "0.1.0"
description = "Python logging with Google-style output and automatic backtraces"
license = {text = "MIT"}
requires-python = ">=3.8"
